# BULID IMAGE
# TODO: separate build & prod later
FROM node:14-alpine as prod

RUN apk add dumb-init
WORKDIR /app

COPY ./.yarnrc ./

COPY ./tsconfig.json .
COPY ./package.json .
COPY ./yarn.lock .

RUN yarn install

COPY ./src ./src

RUN yarn build

ENV NODE_ENV production
ENTRYPOINT ["dumb-init", "node", "/app/dist/index.js"]