name: schedule-e2e-tests

on:
  workflow_dispatch:

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: "Setup npm"
        run: |
          npm set @proxima-one:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.CI_NPM_TOKEN }}"
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:e2e
